### PR TITLE
Fix BlockRepository setting relation of an object and improve amount …

### LINKED ISSUE #2671: Call to undefined method stdClass::unsetRelation()
## Description

We re getting this error when rendering blocks on preview. [This is the line that might have introduced the bug](https://github.com/area17/twill/commit/463bd594af560da06cd05122d6ef7ebf1e10e361#diff-fdd83a455929e4b24f5499c60bb93849a9c7655eb6ad54ae67e2c6b6c19c0299R54).

### Steps to reproduce

It's being generated by having browsers to related items in the block editor.

### Versions

Twill version: 3.4
Laravel version: 11
PHP version: 8.3

/cc @Tofandel

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes #2671 

And improve saving performance by avoiding uneccessary queries

### CODE REVIEW

File: src/Repositories/BlockRepository.php [hunk 1]
```diff
@@ -35,42 +33,37 @@ public function getCrops(string $role): array
...
+                    'subject_type' => $model->getMorphClass(),
+                    'related_id' => $item['id'],
+                    'related_type' => $item['endpointType'],
+                    'browser_name' => $browserName,
+                    'position' => $position,
+                ])
+            )
+        );
+
+        $model->setRelation('relatedItems', $relatedItems);
```
Comment (Tofandel) [inline src/Repositories/BlockRepository.php:47]: Maybe here if we're gonna use the items anyways we can do $model->loadMissing('relatedItems.related') to do just one eager load query instead of one query per model

File: src/Repositories/BlockRepository.php [hunk 2]
```diff
@@ -35,42 +33,36 @@ public function getCrops(string $role): array
...
+        if (!empty($fields['browsers'])) {
+            $browserNames = collect($fields['browsers'])->each(function ($items, $browserName) use ($model) {
+                // This will create items or delete them if they are missing
+                $model->saveRelated($items, $browserName);
+            })->keys();
+
+            // Delete all the related items that were emptied
+            RelatedItem::query()->whereMorphedTo('subject', $model)->whereNotIn('browser_name', $browserNames)->delete();
+        } else {
             $model->clearAllRelated();
```
Comment (Tofandel) [inline src/Repositories/BlockRepository.php:65]: This would previously delete and recreate all related items, which is very write intensive on the database for nothing because saveRelated already does an existence check and deletes the deleted ones

**Comment by ifox** [comment]
Thanks @Tofandel, can you make sure to test the 3 following things:
- changes in a browser in a block render in the Editor previews and full preview
- changes in a browser outside a block render in the full preview
- changes in a browser in a child repeater in a block render in the Editor previews and full preview

**Comment by antonioribeiro** [comment]
Hey @Tofandel, I didn't test this extensively yet but looks like you fixed it, I was able to reproduce the error here and when switching to your branch I don't have it anymore. Thank you!

**Review by ifox — APPROVED** [review]
