### PR TITLE
#1351: Add crop missing exception

### LINKED ISSUE #1351: Throw an error if a crop that does not exist is requested.
## Summary

Throw an error if a crop that does not exist is requested.

Bonus: Document scaling of images

### PR DESCRIPTION
**Pull request by haringsrob**
## Description

This pr now throws an exception when a media is found but there is no crop found.

`"message": "Found media but could not find the crop 'test' (View: /Users/rob/Sites/twill/resources/views/site/blocks/example.blade.php)",`

Together with the changes made in #1308, it will be clear during block development that something is missing.

The exception will not be thrown in a production environment.

## Related Issues

Fixes #1351

### CODE REVIEW

File: src/Models/Behaviors/HasMedias.php [hunk 1]
```diff
@@ -42,20 +43,34 @@ public function medias()
...
+            $media = $this->medias->first(function ($media) use ($role, $crop, &$foundMedia) {
+                if (!$foundMedia) {
+                    $foundMedia = $media->pivot->role === $role;
+                }
+
+                return $foundMedia && $media->pivot->crop === $crop;
             });
         }
 
+        if ($foundMedia && !$media && !app()->environment('production')) {
```
Comment (haringsrob) [inline src/Models/Behaviors/HasMedias.php:69]: switch this to app.debug flag.

**Review by ifox — APPROVED** [review]
